### ISSUE TITLE
라이센스 관련

### ISSUE THREAD

**Issue by dadami-io** [GunwooHan/EasyVtuber#1]
라이센스 관련 명시가 자세하게 없는것 같아 질문드립니다. 이런 신박한(?) 것들에 관한걸 다른 분들께 공유하고 싶은데 어디까지의 수정이 가능할까요?

**Comment by GunwooHan** [comment]
안녕하세요!
기본적으로 다른 분이 자유롭게 개발하는걸 막고 싶지 않아 MIT로 게재하였습니다
대신 tha2 폴더 안의 소스코드와 pretrained model은 Talking Head Anime2(https://github.com/pkhungurn/talking-head-anime-2-demo) repo에 있는 라이센스를 따라주세요
즐거운 하루되세요!

> 라이센스 관련 명시가 자세하게 없는것 같아 질문드립니다. 이런 신박한(?) 것들에 관한걸 다른 분들께 공유하고 싶은데 어디까지의 수정이 가능할까요?

**Comment by dadami-io** [comment]
감사합니다 :)
