### ISSUE TITLE
런타임에러 문의

### ISSUE THREAD

**Issue by jyoonab** [GunwooHan/EasyVtuber#2]
안녕하세요?
해당 프로젝트 다운받아 그대로 돌렸으나 런타임이 발생하여 문의 드립니다. 

`RuntimeError: grid_sampler(): expected input and grid to have same dtype, but input has struct c10::Half and grid has float`

에러가 발생되는 부분은 main.py의 model 부분이고 특이한점은 카메라에 얼굴이 없다면 프로그램 자체가 멈춰버리는것으로 확인되고 있습니다.
`output_image = model(input_image, mouth_eye_vector, pose_vector)`

좋은 프로젝트 감사드리고 
혹시 아시는것이 있다면 답장 부탁드리겠습니다 = ] 
감사합니다.

**Comment by jyoonab** [comment]
![image](https://user-images.githubusercontent.com/37427419/146928616-88fda77b-aeb2-4c69-8fa2-0e25438db710.png)
해당 에러 스크린샷 올려드립니다.

**Comment by GunwooHan** [comment]
안녕하세요!
half precision을 적용한 상태로 진행했었는데, 제가 수정한 소스를 누락했네요 ㅎㅎ;

얼굴이 없는 상태에서 facial pose를 계산하면 에러로 꺼지기 때문에, 얼굴이 없으면 잡힐 때까지 프레임이 업데이트 되지 않도록 해놓았습니다
다시 얼굴이 잡히면 정상적으로 프레임이 업데이트 될건데, 혹시 더 좋은 아이디어 있으시다면 issue에 남겨주시거나 아니면 PR 하시면 검토하겠습니다!

**Comment by jyoonab** [comment]
네 감사드립니다 = ] 
코드 정상적으로 작동되는거 확인되고요 
만약 제안 할만것이 있다면 다른 이슈로 말씀드리겠습니다~
