### ISSUE TITLE
Mediapipe is not working with python 3.8.2

### ISSUE THREAD

**Issue by thanisornsr** [GunwooHan/EasyVtuber#3]
Hi, 
I tried to install media pipe with pip install mediapipe with python 3.8.2. 

I got an error that 
"
  Could not find a version that satisfies the requirement mediapie (from versions: )
No matching distribution found for mediapie
"

Do you have any idea how to get it to install?

BR,
Than

**Comment by GunwooHan** [comment]
![image](https://user-images.githubusercontent.com/76226252/162545706-f7cea3fa-d251-4d9e-8bd8-89ba693640b2.png)

Hi! Than

I think  it's not because of the version
I tried make virtual env (python 3.8.2) and installed medipipe but it works well in anaconda
Where did you test it?

**Comment by thanisornsr** [comment]
Hi,
Thanks for info. 
I was using virtual env in pycharm. I will try it with Conda!
